server:
  port: 8080 # 端口

#激活dev环境配置

spring:
  profiles.active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/pethome?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
